language: r
sudo: required
cache: packages
dist: trusty

compiler:
  - clang

apt_packages:
  - libudunits2-dev

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin libv8-dev

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: fee+yd3SW53ASTFm0ZH3/HKD7wUn1zJL+LHbwJErIMhAemo2FcNaLDGF5TXLuVCSMMnIE+rc8c8NEH0Mf+Jw4+EiZEfEsbu4Ai5xxx81jCJV3sCRAQZG+Tpes+zR3rnxxs7LyM9EcVGf/ypMCLREdAM1rluNrbAe14DZI0b4pjw=

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="https://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - BOOTSTRAP_LATEX=""
