language: r
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin

r_packages:
  - rgdal
  - ncdf4
  - taxize
  - leaflet
  - purrr
  - ggmap
  - ropenaq

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=FALSE

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: fee+yd3SW53ASTFm0ZH3/HKD7wUn1zJL+LHbwJErIMhAemo2FcNaLDGF5TXLuVCSMMnIE+rc8c8NEH0Mf+Jw4+EiZEfEsbu4Ai5xxx81jCJV3sCRAQZG+Tpes+zR3rnxxs7LyM9EcVGf/ypMCLREdAM1rluNrbAe14DZI0b4pjw=
