language: r

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libv8-dev
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libgdal1h

r_binary_packages:
  - rgdal

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: fee+yd3SW53ASTFm0ZH3/HKD7wUn1zJL+LHbwJErIMhAemo2FcNaLDGF5TXLuVCSMMnIE+rc8c8NEH0Mf+Jw4+EiZEfEsbu4Ai5xxx81jCJV3sCRAQZG+Tpes+zR3rnxxs7LyM9EcVGf/ypMCLREdAM1rluNrbAe14DZI0b4pjw=

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
